version: '2.3'

services:
#    """ Service Gateway """
    service-gateway:
      image: mask-rcnn-api_service-gateway
      ports:
        - "8888:8888"
      volumes:
        - ${PWD}:/app
      networks:
        fetal-head-estimator:
          aliases:
            - servicegateway
      working_dir: /app
      entrypoint: ["python", "service_gateway/service_gateway.py"]
#      restart: always

#    """ Center Processing """
    center-processing:
      image: mask-rcnn-api_center-processing
      ports:
        - "8100:8100"
      volumes:
        - ${PWD}:/app
      networks:
        fetal-head-estimator:
          aliases:
            - centerprocessing
      working_dir: /app
      entrypoint: [ "python", "center_processing/center_processing.py" ]

#    """ Mask RCNN """
    mask-rcnn:
      image: mask-rcnn-api_mask-rcnn
      ports:
        - "8200:8200"
      volumes:
        - ${PWD}:/app
      networks:
        fetal-head-estimator:
          aliases:
            - maskrcnn
      working_dir: /app
      entrypoint: [ "python", "mask_rcnn/mrcnn_api.py" ]

#    """ Ellipse Fitter """
    ellipse-fitter:
      image: mask-rcnn-api_ellipse-fitter
      ports:
        - "8300:8300"
      volumes:
        - ${PWD}:/app
      networks:
        fetal-head-estimator:
          aliases:
            - ellipse
      working_dir: /app
      entrypoint: [ "python", "ellipse_fitter/ellipse_api.py" ]

#    """ Perimeter Estimator """
    perimeter-estimator:
      image: mask-rcnn-api_perimeter-estimator
      ports:
        - "8400:8400"
      volumes:
        - ${PWD}:/app
      networks:
        fetal-head-estimator:
          aliases:
            - perimeter
      working_dir: /app
      entrypoint: [ "python", "perimeter_estimator/perimeter_api.py" ]

networks:
    fetal-head-estimator:
      external: true
